- hydrabooster/run-node.go
- hydrabooster/spawn-node.go
- main.go
Returns wrapped errors* (to provide context) up to main. At the top level we `panic(err)`...or perhaps we should `log.Fatalln(err)` instead?
\* with `%w` - see https://golang.org/pkg/fmt/#Errorf
> refactor: propagate errors

- hydrabooster/run-node.go
- hydrabooster/spawn-node.go
- hydrabooster/spawn-node_test.go
Adds a basic test to ensure spawning a node works successfully.
ALSO! Does a little refactoring to `spawnNode` to make it return a channel on which we can receive status updates for progress on connecting to a bootstrap node.
It allows us to test this function better by being told when the boostrap process is complete instead of checking a global internal int64 variable `bootstrapDone` periodically.
Previously `spawnNode` it just incremented `bootstrapDone,` but now each call to `spawnNode` will know exactly when it is bootstrapped and which node became bootstrapped.
The `bootstrapDone` global internal variable has moved to `run-node.go` which may/may not be refactored away at a later date.
COVERAGE FTW! https://codecov.io/gh/libp2p/hydra-booster/commits
> test: add spawn node test

- go.mod
- node/node.go
- node/opts/options.go
Also adds a `RoutingTable` option (which is currently ignored)
> feat: expose datastore and routing table on hydra node

- Dockerfile
- README.md
- main.go
Allows us to dynamically increase/decrease the number of sybils a hydra spawns via the `HYDRA_MANY` env var. This means that we do not need to commit, tag and publish a new docker image version when we want to tweak the value :)
Also exposes the HTTP API and `/metrics` ports.
> feat: allow num sybils to be set via env var

- Dockerfile
- main.go
- metrics/metrics.go
resolves #45
Also:
* changes `-metrics-port` to `-metrics-addr` for consistency and flexibility.
* changes `-portBegin`, `-bucketSize` and `-bootstrapConc` to kebab case `-port-begin`, `-bucket-size` and `-bootstrap-conc` for consistency.
* removes the ability to _not_ expose metrics server (since UI depends on them). Do not want it public? Specify `127.0.0.1:8888` as the `-metrics-addr`.
> fix: specify httpapi address

- Dockerfile
No need to log out metrics we're collecting via grafana.
> chore: remove UI in production

- main.go
Random number generator needs to be seeded or it's deterministic.
The hydra nodes are selecting the same bootstrap node.
> fix: random bootstrap peer selection

- hydra/periodicmetrics.go
- ui/ui.go
It allocates a timer every time and can't be canceled. It's better and often simpler to just use a timer.
> chore: avoid time.After

- ui/ui.go
We only call Render once, so this shouldn't be a huge issue.
> fix: don't leak the ticker

- README.md
- head/head.go
- main.go
- version/version.go
Adds a `version.go` file which we'll attempt to keep updated when releasing so that when collecting stats we can see the version that is being run.
Also, directly setting `identify.ClientVersion` is deprecated.
> feat: user agent with correct version

- README.md
- datastore/postgres.go
- go.mod
- go.sum
- hydra/hydra.go
- main.go
This PR adds a [sql-datastore](https://github.com/whyrusleeping/sql-datastore) and enables connecting to a PostgreSQL database for the datastore.
This enables a datastore that'll persist across restarts and that can be shared by multiple Hydras.
The PostgreSQL datastore can be enabled by passing a postgres connection string with the `-db` flag or by using the `HYDRA_DB` env variable.
We need the following PRs to land so we can switch from my fork (in this order):
resolves https://github.com/libp2p/hydra-booster/issues/20
> feat: add PostgreSQL datastore

- .gitignore
- README.md
- datastore/postgres.go
- datastore/proxy.go
- docs/deployment.md
- go.mod
- go.sum
- httpapi/httpapi.go
- hydra/hydra.go
- hydra/metricstasks.go
- k8s/alasybil.yaml
- k8s/bubbles.yaml
- k8s/chumpy.yaml
- k8s/domino.yaml
- k8s/euclid.yaml
- k8s/flake.yaml
- k8s/grendel.yaml
- k8s/hojo.yaml
- k8s/ibycus.yaml
- k8s/jetta.yaml
- main.go
- metrics/definitions.go
- metrics/metrics.go
Persistent and shared SQL datastore seems to be working finally!
(Different results because everyone is counting # records at slightly different times)
TODO: Not every hydra needs to count provider records if they're sharing the same datastore!
> feat: postgres

- k8s/alasybil.yaml
- k8s/bubbles.yaml
- k8s/chumpy.yaml
- k8s/domino.yaml
- k8s/euclid.yaml
- k8s/flake.yaml
- k8s/grendel.yaml
- k8s/hojo.yaml
- k8s/ibycus.yaml
- k8s/jetta.yaml
Do not NAT inbound connections or Hydra heads receive incorrect remote addresses for Peers.
> fix: disable k8s NAT

- httpapi/httpapi.go
15s is not a lot of time to read or write the entire response especially when we have 100k of peer addresses to respond with.
> fix: increase read timeout

- README.md
- main.go
Closes #112.
Once merged, the default port should be added here: 
https://github.com/prometheus/prometheus/wiki/Default-port-allocations
> Change default metrics listener to 127.0.0.1:9758

- README.md
- go.mod
- go.sum
- head/head.go
- head/head_test.go
- head/opts/options.go
- hydra/hydra.go
- hydra/hydra_test.go
- k8s/alasybil.yaml
- k8s/bubbles.yaml
- k8s/chumpy.yaml
- k8s/domino.yaml
- k8s/euclid.yaml
- k8s/flake.yaml
- k8s/grendel.yaml
- k8s/hojo.yaml
- k8s/ibycus.yaml
- k8s/jetta.yaml
- main.go
This PR updates the libp2p-kad-dht dependency, which removes the v1 compat option (v2 did not happen in the end).
resolves #110
> chore: update libp2p-kad-dht dependency

- Dockerfile
- utils/port-selector_test.go
Using an Alpine build image and then creating a run-image with only bare necessities.
Perhaps I'm not measuring right but I think I've gotten down to 50 MB from 450 MB for the whole Debian shebang.
> Optimised Docker build

- datastore/proxy.go
- head/head.go
- httpapi/httpapi.go
- main.go
- ui/gooey.go
This is the naive approach to fixing each staticcheck warning.
`color()`, `printDataSharedLine()` in gooey, and `randBootstrapAddr()` head seem reasonable, even if they aren't (yet) called anywhere. Should we selectively ignore this lint warning, or just comment them out?
> Fix staticcheck

- README.md
- go.mod
- head/head.go
- head/opts/options.go
- hydra/hydra.go
- idgen/idgen.go
- main.go
I think this addresses #128 quite neatly, I took some advice from @Kubuxu to use the HKDF and looking over how we did stuff in go-libp2p-core/crypto but im pretty new to Go
> Allow deterministic key generation from seed

- head/head.go
DHT clients expect messages to contain raw multihashes, not CIDs. This works for CIDv0 but not CIDv1, since a raw CIDv0 is a raw multihash but a raw CIDv1 is not.
I believe the impact of this is that hydras will not find providers for CIDv1's added via Head.AddProvider (I believe the provider prefetching uses this), since clients will be requesting a different key than what was used in the datastore.
> Use raw multihash instead of raw CID as key in Head.AddProvider()

- metrics/definitions.go
The motivation is that we are getting some errors from Prometheus
because of the cardinality created by the large # buckets.
For many latency metrics we just need ballpark figures, we don't need
fine-grained numbers.
> Use less buckets for some latency metrics

- go.mod
- providers/storetheindex/findproviders.go
- providers/storetheindex/mockserver.go
Currently, all provider records coming back from storetheindex are being returned to clients.
We should filter that implicitly to only providers advertising bitswap while clients are implicitly expecting that behavior.
> Filter bitswap records for hydras

- .github/workflows/docker.yml
For some reason the asterisk wildcard has stopped working, but removing the condition entirely works.
This is from the docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
> fix: remove wildcard from Docker build push event

- httpapi/httpapi.go
- httpapi/httpapi_test.go
We want to correlate provider records with their corresponding peer records to get a sense of content replication and content locality (inferred from multi addresses).
Hydras are currently running with an in-memory peerstores (one for each head) and there's (afaik) no way to access/dump them.
An alternative that we considered was to switch from an in-memory peerstore to a LevelDB-backed one and export data from there. However, only a single process (possibly multi-threaded) can access a particular LevelDB database at a time. This means we're back at square one.
This PR adds an endpoint that loops through all hydra+heads plus all peers in their peerstores and serves their information (PeerID, multiaddresses, agent version, supported protocols) to the requesting client.
> feat: add peer store export http endpoint

- providers/reframe.go
This line must be a leftover from debugging. It heavily pollutes sdtout.
> Remove an fmt.Println(numPeers) line

- hydra/hydra.go
- main.go
- providers/noop.go
- providers/reframe.go
This will allow the hydras to run in a mode where they look like DHT nodes, and accept writes, but silently discard the writes and always return only results from indexers.
> Allow discarding writes with reframe

- Dockerfile
The new version has some backwards-incompatible change in OpenSSL causing runtime errors. We should upgrade this later, this is a stopgap.
> Pin alpine version

- go.mod
- go.sum
- hydra/hydra.go
- metrics/metrics.go
- providers/httpapi.go
- providers/reframe.go
Example metrics output:
Run with: `./hydra -nheads 100 -port-begin 30000 -disable-prefetch -provider-store https://cid.contact -name gus`
```
$ curl -s http://127.0.0.1:9758/metrics | grep routing_http
hydrabooster_routing_http_client_latency_bucket{code="200",error="None",host="cid.contact",name="gus",operation="FindProviders",le="1"} 0
hydrabooster_routing_http_client_latency_bucket{code="200",error="None",host="cid.contact",name="gus",operation="FindProviders",le="2"} 0
hydrabooster_routing_http_client_latency_bucket{code="200",error="None",host="cid.contact",name="gus",operation="FindProviders",le="5"} 0
hydrabooster_routing_http_client_latency_bucket{code="200",error="None",host="cid.contact",name="gus",operation="FindProviders",le="10"} 0 …
```
> feat: add support for delegated routing HTTP API

- head/head.go
- head/opts/options.go
- hydra/hydra.go
- main.go
This exposes the ability to set HighWater, LowWater and GracePeriod for the libp2p connection manager.
> Allow configuring connection manager's limits
